version: "3.9"

services:
  db:
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: ${DB_DATA_PATH}
    image: postgres
    networks:
      - project
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:${DB_DATA_PATH}

  web:
    build:
      context: ..
      dockerfile: ./deployment/dockerfiles/backend/Dockerfile
    command: 
      - ./deployment/scripts/wait-for-postgres.sh
      - ./deployment/scripts/uvicorn.sh
    container_name: web
    depends_on:
      - db
    environment:
      - WEB_PORT
      - LEVEL
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - HOST
    image: backend
    networks:
      - project
      - nginx
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - ../backend/deployment:/opt/app/deployment
      - ../backend/templates:/opt/app/templates
      - ../backend/public:/opt/app/public
      - ../backend/src:/opt/app/src

networks:
  project:
    name: project
    driver: bridge

  nginx:
    external:
      name: nginx

volumes:
  db-data:
    name: backend_db-data
